apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rendermart
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3300