apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rendermart
data:
  PORT: "3300"
  DB_HOST: "postgres.rendermart-db.svc.cluster.local"
  DB_NAME: "rendermart"
  CORS_ORIGIN: "k8s-renderma-ingress-77a757caa3-1662937834.us-east-1.elb.amazonaws.com"
