apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: rendermart
build:
  tagPolicy:
    customTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  local:
    push: true
  artifacts:
    - image: 061039783359.dkr.ecr.us-east-1.amazonaws.com/rendermart-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: 061039783359.dkr.ecr.us-east-1.amazonaws.com/rendermart-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/config/namespace-rendermart-db.yaml
    - k8s/config/namespace-rendermart.yaml
    - k8s/postgres/postgres-secret-db.yaml
    - k8s/postgres/postgres-secret.yaml
    - k8s/postgres/postgres-service.yaml
    - k8s/postgres/postgres-pvc.yaml
    - k8s/postgres/postgres-statefulset.yaml
    - k8s/backend/backend-config.yaml
    - k8s/backend/backend-deployment.yaml
    - k8s/backend/backend-service.yaml
    - k8s/frontend/frontend-config.yaml
    - k8s/frontend/frontend-deployment.yaml
    - k8s/frontend/frontend-service.yaml
    - k8s/redis/redis-secret.yaml
    - k8s/config/ingress.yaml
