apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: rendermart
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-cookie-path: "/;/"
    nginx.ingress.kubernetes.io/session-cookie-name: "session_token"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/ # Toutes les requêtes qui commencent par /api vont au backend
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80

          - path: / # Tout le reste va au frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80