name: Deploy to EKS with Skaffold

on:
  push:
    branches:
      - main # Déclenchement sur push vers main

jobs:
  deploy:
    name: Build & Deploy with Skaffold
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }} --role-arn arn:aws:iam::061039783359:role/YOUR_EKS_ROLE

      - name: Debug EKS Connection
        run: |
          aws eks describe-cluster --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Vérifier le contexte `kubectl`
        run: kubectl config current-context

      - name: Test kubectl connection
        run: kubectl get nodes -v=10

      - name: Ensure IAM user is in aws-auth ConfigMap
        run: |
          USER_ARN="arn:aws:iam::061039783359:user/hamza"
          if ! kubectl get configmap -n kube-system aws-auth -o yaml | grep -q "$USER_ARN"; then
            echo "Adding user $USER_ARN to aws-auth"
            kubectl get configmap -n kube-system aws-auth -o yaml > aws-auth.yaml
            echo "  - userarn: $USER_ARN" >> aws-auth.yaml
            echo "    username: hamza" >> aws-auth.yaml
            echo "    groups:" >> aws-auth.yaml
            echo "      - system:masters" >> aws-auth.yaml
            kubectl apply -f aws-auth.yaml
          else
            echo "User $USER_ARN is already in aws-auth"
          fi

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin/

      - name: Deploy with Skaffold
        run: skaffold run
